name       : libpng
version    : 1.6.39
release    : 23
source     :
    - https://kumisystems.dl.sourceforge.net/project/libpng/libpng16/1.6.39/libpng-1.6.39.tar.xz : 1f4696ce70b4ee5f85f1e1623dc1229b210029fa4b7aee573df3e2ba7b036937
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
builddeps  :
    - pkgconfig32(zlib)
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static --enable-intel-sse
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check
