name       : libpng
version    : 1.6.35
release    : 17
source     :
    - https://vorboss.dl.sourceforge.net/project/libpng/libpng16/1.6.35/libpng-1.6.35.tar.xz : 23912ec8c9584917ed9b09c5023465d71709dce089be503c7867fec68a93bcd7
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
builddeps  :
    - pkgconfig32(zlib)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check
