name       : libpng
version    : 1.5.28
release    : 12
source     :
    - https://pilotfiber.dl.sourceforge.net/project/libpng/libpng15/1.5.28/libpng-1.5.28.tar.xz : 1c3a2d939b6729de493ebc0b14aeaa1bdc4ffa80a75d2506bb2c75a0ff3ac8e9
homepage   : http://www.libpng.org/pub/png/libpng.html
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
builddeps  :
    - pkgconfig32(zlib)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
