name       : libpng
version    : 1.6.34
release    : 16
source     :
    - ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng16/libpng-1.6.34.tar.xz : 2f1e960d92ce3b3abd03d06dfec9637dfbd22febf107a536b44f7a47c60659f6
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
builddeps  :
    - pkgconfig32(zlib)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-13785.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check || :
