name       : libpng
version    : 1.5.30
release    : 13
source     :
    - ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng15/libpng-1.5.30.tar.xz : 7d76275fad2ede4b7d87c5fd46e6f488d2a16b5a69dc968ffa840ab39ba756ed
homepage   : http://www.libpng.org/pub/png/libpng.html
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
builddeps  :
    - pkgconfig32(zlib)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
