name        : libpng
version     : 1.5.26
release     : 7
source      :
    - http://prdownloads.sourceforge.net/libpng/libpng-1.5.26.tar.gz : 5bfc3c29c9c5551f6fa39e352121e8d9e3d6eb5093b72a7a9cff0a232962ae51
homepage    : http://www.libpng.org/pub/png/libpng.html
license     :
    - Libpng
summary     : libpng (Official PNG reference library)
builddeps   :
    - pkgconfig(zlib)
description : |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel: /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
