name       : libpng
version    : 1.6.38
release    : 22
source     :
    - https://kumisystems.dl.sourceforge.net/project/libpng/libpng16/1.6.38/libpng-1.6.38.tar.xz : b3683e8b8111ebf6f1ac004ebb6b0c975cd310ec469d98364388e9cedbfa68be
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
builddeps  :
    - pkgconfig32(zlib)
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static --enable-intel-sse
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check
