name       : libpng
version    : 1.6.37
release    : 19
source     :
    - https://vorboss.dl.sourceforge.net/project/libpng/libpng16/1.6.37/libpng-1.6.37.tar.xz : 505e70834d35383537b6491e7ae8641f1a4bed1876dbfe361201fc80868d88ca
homepage   : http://www.libpng.org/pub/png/
license    : Libpng
component  : multimedia.library
summary    : libpng (Official PNG reference library)
builddeps  :
    - pkgconfig32(zlib)
description: |
    libpng is the official PNG reference library, supporting almost all PNG features and has been extensively tested.
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
        - /usr/bin/libpng*-config
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.la
check      : |
    %make check
